name: Python Code Checks

on:
  push:
    branches:
      - "**" # Triggers on all branches
  pull_request:
    branches:
      - "**" # Triggers on all pull requests

jobs:
  lint_and_security:
    name: Run Ruff and Bandit
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install Ruff and Bandit
      - name: Install Ruff and Bandit
        run: |
          pip install ruff bandit

      # Run Ruff for linting
      - name: Run Ruff
        run: |
          ruff . --exit-zero

      # Run Bandit for security checks
      - name: Run Bandit
        run: |
          bandit -r . -f txt
